### ISSUE TITLE
Error - Unable to fetch data from HERE: Invalid lang value

### ISSUE THREAD

**Issue by kloggy** [eifinger/hass-here-weather#193]
I'm having a problem since v3 (currently running 3.0.2) as in the title

![image](https://user-images.githubusercontent.com/38220016/209641660-9fb9744a-f78a-48ac-af5f-f74b747c386b.png)

From the log

```
Logger: homeassistant.config_entries
Source: config_entries.py:1113
First occurred: 15:59:17 (1 occurrences)
Last logged: 15:59:17

Config entry 'here_weather' for here_weather integration not ready yet: Unable to fetch data from HERE: Invalid lang value.; Retrying in background
```

I set the language to English
But I am not sure it keeps the setting or if the pop up is just too small to show it?

![image](https://user-images.githubusercontent.com/38220016/209691439-59453aa0-9158-4182-b2ed-41a33829a268.png)

**Comment by eifinger** [comment]
Thank you for reporting this error. You can set the language to `English_US` as a temporary workaround

**Comment by eifinger** [comment]
Note to self: Evaluate https://github.com/phlax/python-bcp47/
